# Generated by Django 3.1.5 on 2021-07-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.ImageField(default='Image', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='post',
            field=models.TextField(max_length=1000),
        ),
    ]
