# Generated by Django 3.2 on 2021-07-13 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0002_auto_20210713_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='current_user',
            new_name='user',
        ),
    ]
