# Generated by Django 3.1.5 on 2021-07-10 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instapp', '0002_auto_20210709_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='likes',
            field=models.ManyToManyField(related_name='post_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photos',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instapp.editor'),
        ),
    ]
