# Generated by Django 3.2 on 2021-07-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0003_rename_current_user_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilephoto',
            field=models.ImageField(upload_to='', verbose_name='image'),
        ),
    ]
