# Generated by Django 3.2 on 2021-07-11 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0005_auto_20210711_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='image',
            new_name='img',
        ),
    ]
