# Generated by Django 3.2 on 2021-07-11 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0006_rename_image_comment_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='img',
            new_name='image',
        ),
    ]
