# Generated by Django 3.2 on 2021-07-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0009_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='current_user',
        ),
    ]
